services:
  - type: web
    name: schema-extractor
    runtime: python
    buildCommand: ./install_chrome.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
